# -----------------------------------------------------
# |            Plot System - by Alps BTE
# -----------------------------------------------------
# | [Github Repo] https://github.com/AlpsBTE/PlotSystem
# | [Config Documentation] https://github.com/AlpsBTE/PlotSystem/wiki/Configuration
# | [Contacts - Discord] R3tuxn#7169, Cinnazeyy#2440
# -----------------------------------------------------

# The lobby world, where all players are teleported to, whenever they join or leave a plot
# [default] -> Uses the default multiverse spawn world
spawn-world: default

# Keep updated about newer versions
check-for-updates: true

# Enables special dev tools and features for development
# NOTE: Do not change if you do not know what you are doing
dev-mode: false


# -----------------------------------------------------
# | Supported database: MariaDB
# -----------------------------------------------------
database:
  url: jdbc:mariadb://adress:3306/
  dbname: plotsystem
  username: plotsystem
  password: minecraft


# -----------------------------------------------------
# | Terra-Servers: Register one or multiple terra servers
# |
# | Only use FTP/SFTP if the servers cannot communicate with each other using Symlinks
# | For more information: https://github.com/AlpsBTE/PlotSystem/wiki/Configuration
# -----------------------------------------------------
servers:
  S1:
    server-name: server-1
    schematic-path: default
    ftp:
      enabled: false
      address: ip-adress
      port: 22
      username: user
      password: paswd


# -----------------------------------------------------
# | Countries: Register one or multiple countries and assign them to a server
# |
# | Head-ID -> Displays the head for the country/region. Use this website to get a head (https://minecraft-heads.com/custom-heads)
# | Server -> Each country must be linked to a server registered above
# | For more information: https://github.com/AlpsBTE/PlotSystem/wiki/Configuration
# -----------------------------------------------------
countries:
  AT:
    head-id: 4397
    server: S1
  CH:
    head-id: 32348
    server: S1
  LI:
    head-id: 26174
    server: S1


# -----------------------------------------------------
# | Holograms: Show plot statistics / Are placed in the spawn world
# | NOTE: Requires the HolographicDisplays plugin to work
# -----------------------------------------------------
holograms:
  # Displays the top 10 builders with the highest score
  score-leaderboard:
    enabled: false
    x: 0
    y: 0
    z: 0
  # Displays the top 10 players with the most completed buildings
  completed-builds-leaderboard:
    enabled: false
    x: 0
    y: 0
    z: 0

# Switch hologram statistics between different time stamps
# [interval] -> default: 5 seconds
display-options:
  interval: 5
  show-daily: false
  show-weekly: true
  show-monthly: true
  show-yearly: false


# -----------------------------------------------------
# | Navigation: The command that the player will automatically execute when pressing the navigator item in the companion
# | NOTE: Remove the "/" from whatever command you want to use
# -----------------------------------------------------
navigator:
  item: NETHER_STAR
  name: Navigator
  description: Open the navigator menu
  command: navigator


# -----------------------------------------------------
# | Formatting: Info/Error message outputs
# -----------------------------------------------------
message-prefix: §7§l>>
info-prefix: §a
error-prefix: §c


# NOTE: Do not change
config-version: 1.0