# -------------------------------------------
#         Plot System - by Alps BTE
# -------------------------------------------
# [Github Repo] https://github.com/AlpsBTE/PlotSystem
# [Config Documentation] https://github.com/AlpsBTE/PlotSystem/wiki/Configuration
# [Contacts - Discord] R3tuxn#7169, Cinnazeyy#2440
# -------------------------------------------
database:
  url: jdbc:mariadb://IP:PORT/
  name: name
  username: username
  password: password
outlines-schematic-path: path
lobby-world: world
spawn-point:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
holograms:
  ScoreLeaderboard:
    enabled: true
    x: 0
    y: 0
    z: 0
  ParkourLeaderboard:
    enabled: false
    x: 0
    y: 0
    z: 0
  EventHologram:
    enabled: false
    x: 0
    y: 0
    z: 0
  BuildsLeaderboard:
    enabled: true
    x: 0
    y: 0
    z: 0
countries:
  AT:
    head-id: 4397
    finished-schematic-path: path
  CH:
    head-id: 32348
    finished-schematic-path: path
  LI:
    head-id: 26174
    finished-schematic-path: path