#BTE-PlotSystem Configuration File
database:
  username: null
  password: null
schematic-path: null
leaderboard:
  x: 0
  y: 0
  z: 0
  world: null
spawn-point:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0