main: github.BTEPlotSystem.BTEPlotSystem
version: 1.0
api-version: 1.12.2
name: AlpsBTE-PlotSystem
author: R3tuxn & Cinnazeyy
depend: [HeadDatabase, HolographicDisplays]

commands:
  plot:
    description: teleport to a plot
    permission: alpsbte.admin
    usage: /plot <ID>
  submit:
    description: submit a plot
    permission: alpsbte.plot
    usage: /submit, /submit <ID>
  abandon:
    description: abandon a plot
    permission: alpsbte.plot
    usage: /abandon, /abandon <ID>
  undosubmit:
    description: undo a submission of a plot
    permission: alpsbte.plot
    usage: /undosubmit, /undosubmit <ID>
  review:
    description: review unreviewed plots
    permission: alpsbte.review
    usage: /review
  companion:
    description: opens the companion menu UI
    permission: alpsbte.companion
    usage: /companion
  generateplot:
    description: generate a new plot
    permission: alpsbte.admin
    usage: /generateplot <ID>
  sethologram:
    description: sets the position of a hologram
    permission: alpsbte.admin
    usage: /sethologram <name>
  reloadhologram:
    description: reloads all holograms
    permission: alpsbte.admin
    usage: /reloadhologram
  spawn:
    description: teleports you back to the spawn location
    usage: /spawn
  tpp:
    description: teleport to a player
    usage: /tpp <Player>
  link:
    description: sends you the links of the plot you are currently on
    usage: /link
  plots:
    description: shows all plots of the given player
    permission: alpsbte.plot
    usage: /plots, /plots <Player>
  feedback:
    description: shows all feedback information of a plot
    permission: alpsbte.plot
    usage: /feedback <ID>
  sendfeedback:
    description: sets the feedback of a plot
    permission: alpsbte.review
    usage: /sendfeedback <ID> <Text>
  edit:
    description: enable/disble build permissions for reviewers on plots
    permission: alpsbte.review
    usage: /edit
  undoreview:
    description: undo a review of a plot
    permission: alpsbte.review
    usage: /undoreview <ID>
permissions:
  alpsbte.admin:
    description: manager permissions