main: github.BTEPlotSystem.BTEPlotSystem
version: 1.0
api-version: 1.12.2
name: BTE-PlotSystem
author: R3tuxn & Cinnazeyy

commands:
  coords:
    description: get player coordinates
    usage: /coords
    permission: plot.coords