main: github.BTEPlotSystem.BTEPlotSystem
version: 1.0
api-version: 1.12.2
name: AlpsBTE-PlotSystem
author: R3tuxn & Cinnazeyy
depend: [HeadDatabase, HolographicDisplays]

commands:
  plot:
    description: teleport to a plot
    usage: /plot <ID>
    permission: alpsbte.plot
  finish:
    description: finish a plot
    usage: /finish
    permission: alpsbte.finish
  abandon:
    description: abandon a plot
    usage: /abandon
    permission: alpsbte.abandon
  review:
    description: review unreviewed plots
    usage: /review
    permission: alpsbte.review
  companion:
    description: opens the companion UI
    usage: /companion
    permission: alpsbte.companion
  generateplot:
    description: generate a new plot
    usage: /generateplot <ID>
    permission: alpsbte.generateplot
  sethologram:
    description: sets the position of a hologram
    usage: /sethologram <name>
    permission: alpsbte.hologram
  reloadhologram:
    description: reloads all holograms
    usage: /reloadhologram
    permission: alpsbte.hologram
  spawn:
    description: teleports you back to the spawn location
    usage: /spawn
    permission: alpsbte.companion
  tpp:
    description: teleport to a player
    usage: /tpp <Player>
    permission: alpsbte.tpp