main: github.BTEPlotSystem.BTEPlotSystem
version: 1.0
api-version: 1.12.2
name: AlpsBTE-PlotSystem
author: R3tuxn & Cinnazeyy
depend: [HeadDatabase, HolographicDisplays]

commands:
  review:
    description: review unreviewed plots
    usage: /review
    permission: alpsbte.review
  companion:
    description: opens the companion UI
    usage: /companion
    permission: alpsbte.companion
  generateplot:
    description: generate a new plot
    usage: /generateplot <ID>
    permission: alpsbte.generateplot
  hub:
    description: teleports you back to the hub
    usage: /hub
    permission: alpsbte.hub
  setleaderboardposition:
    description: sets the position of the leaderboard
    usage: /setleaderboardposition
    permission: alpsbte.leaderboard